{{- $relname := .Release.Name -}}
{{- $pullsecrets := .Values.deployments.imagePullSecrets -}}
{{- $target := .Values.target -}}
{{- with .Values.deployments.dashboard }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $relname }}-nodecg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $relname }}-nodecg
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $relname }}-nodecg
    spec:
      containers:
      - name: {{ $relname }}-nodecg
        image: {{ .container }}:{{ .version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .port }}
        volumeMounts:
            - mountPath: /nodecg/db
              name: {{ $relname }}-nodecg-db
            - mountPath: /nodecg/logs
              name: {{ $relname }}-nodecg-db
      {{- if ne $target "digitalocean" }}
      imagePullSecrets: 
        - name: {{ $pullsecrets }}
      {{- end }}
      volumes:
        - name: {{ $relname }}-nodecg-db
          persistentVolumeClaim:
            claimName: {{ $relname }}-claim
{{- end }}
{{- if .Values.deployments.rtmp.controller }}
{{- with .Values.deployments.rtmp.controller }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $relname }}-rtmp-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $relname }}-rtmp-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $relname }}-rtmp-controller
    spec:
      containers:
      - name: {{ $relname }}-rtmp-controller
        image: {{ .container }}:{{ .version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .port}}
        env:
        {{- range $key, $val := .env }}
          - name: {{ $key }}
            value: {{ $val | quote}}
        {{- end }}
        volumeMounts:
            - mountPath: /code/db
              name: {{ $relname }}-rtmp-controller-db
      volumes:
        - name: {{ $relname }}-rtmp-controller-db
          persistentVolumeClaim:
            claimName: {{ $relname }}-rtmp-controller-claim
      {{- if ne $target "digitalocean" }}
      imagePullSecrets: 
        - name: {{ $pullsecrets }}
      {{- end }}
---
{{- end }}
{{- end }}