{{- $relname := .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $relname }}-nodecg
spec:
  type: ClusterIP
  ports:
  - name: {{ $relname }}-dashboard
    port: 9090
    targetPort: 9090
{{ if .Values.networking.controller }}
  - name: {{ $relname }}-controller
    port: 80
    targetPort: 80
{{ end }}
  selector:
    app: {{ $relname }}-nodecg
{{ if .Values.networking.dashboard }}
{{- with .Values.networking.dashboard }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $relname }}-dash-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .host | quote}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $relname }}-nodecg
            port:
              number: {{ .port }}
{{ end }}
{{ end }}
{{ if .Values.networking.controller }}
{{- with .Values.networking.controller }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $relname }}-rtmp-controller-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .host | quote}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $relname }}-rtmp-controller
            port:
              number: {{ .port }}
{{ end }}
{{ end }}