target: "digitalocean"
deployments:
  # imagePullSecrets the name of the image pull secrets if needed
  imagePullSecrets: please-remake
  dashboard:
    container: ghcr.io/rodg/nodecg-base
    version: latest
    port: 9090
  rtmp:
    controller:
      container: ghcr.io/rodg/rtmp-controller
      version: latest
      port: 80
      env:
        RTMP_DOMAIN: popola.dev
    server:
      enabled: false
networking:
  dashboard:
    host: example.com
    port: 9090
  controller:
    host: api.example.com
    port: 80
